
services:
  academy-api:
    image: academy-api
    build:
     context: .
     dockerfile: AcademyApi/Dockerfile
     args:
     - LBHPACKAGESTOKEN=${LBHPACKAGESTOKEN}
    ports:
      - 3000:3000
    environment:
      - CONNECTION_STRING=Server=test-database,1433;Database=core;User Id=sa;Password=MyP@w0rd;TrustServerCertificate=yes;
    links:
      - test-database

  academy-api-test:
    image: academy-api-test
    build:
      context: .
      dockerfile: AcademyApi.Tests/Dockerfile
      args:
      - LBHPACKAGESTOKEN=${LBHPACKAGESTOKEN}
    environment:
      - DB_HOST=test-database
    links:
      - test-database

  test-database:
    image: test-database
    build:
      context: .
      dockerfile: database/${DOCKERFILE_DIR}/Dockerfile
    ports:
      - 1433:1433
